kind: pipeline
name: default

steps:
- name: build
  image: alpine
  environment:
    USERNAME:
      from_secret: username

---
kind: secret
name: username
data: DGSnD7/aFcPd0UA5+C0mvwrovGxI5ojIRwl4mpvIR4bTI9s=
