kind: pipeline
name: default

steps:
- name: build3
  image: alpine
  environment:
    USERNAME:
      from_secret: username

---
kind: secret
name: username
data: DSbrEqi95E1aHGp+uICR8u1OegAEpuAA0DJchzpYNIbXopM=
